### PR TITLE
Make `updateLocation` not script crash

### LINKED ISSUE #244: `updateLocation` can script crash when creating a `new URL()`
Please see the diff here, at line 50:

https://github.com/pbeshai/use-query-params/commit/4d7a089b627c4e3ebc6026778bd75522f7f8ec71?diff=split#diff-2b69e8addd21fff5dab3f789e51a2582b63e95e28e393f7319e887d29de174e7

Previously href was calculated this way:
```const href = parseUrl(location.href || '').url + search;```

Now it is this:
```
let href: string;
  if (location.href) {
    const url = new URL(location.href);
    href = `${url.origin}${url.pathname}${search}`;
  } else {
    href = search;
  }
```

If you call the ``updateLocation`` with no ``href``, it will set href to be the search value.
Now if you call updateLocation again, reusing the same location object that was returned, href will be the search value.
This causes an exception at this line:
```const url = new URL(location.href);```
because URL requires a valid URL - "If the given base URL or the resulting URL are not valid URLs, the JavaScript [TypeError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError) exception is thrown." see https://developer.mozilla.org/en-US/docs/Web/API/URL/URL

### PR DESCRIPTION
**Pull request by jmcpeak**
Fix issue where `updateLocation` script crashes

Resolves #244

### CODE REVIEW

File: packages/serialize-query-params/src/updateLocation.ts [hunk 1]
```diff
@@ -10,6 +10,24 @@ const JSON_SAFE_CHARS = `{}[],":`
   .split('')
   .map((d) => [d, encodeURIComponent(d)]);
```
Comment (jmcpeak) [inline packages/serialize-query-params/src/updateLocation.ts:12]: I pulled this out into a named function to allow focusing in on the task at hand

**Comment by pbeshai** [comment]
Looks good, thank you!

**Comment by pbeshai** [comment]
Thank you for a very complete PR! This has been published in serialize-query-params v2.0.2
